# Generated by Django 3.2.9 on 2021-11-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='bs_logo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
